// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioAPI.Data;

#nullable disable

namespace PortfolioAPI.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    partial class PortfolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortfolioAPI.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("PortfolioAPI.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Tech Corp Inc.",
                            Description = "Led development of microservices architecture. Mentored junior developers. Reduced API response time by 40% through query optimisation.",
                            IsCurrent = true,
                            Location = "Remote",
                            Role = "Senior .NET Developer",
                            StartDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Company = "StartupXYZ",
                            Description = "Built and maintained customer-facing web applications using ASP.NET Core and React.",
                            EndDate = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCurrent = false,
                            Location = "Bangalore, India",
                            Role = "Full-Stack Developer",
                            StartDate = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PortfolioAPI.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GithubUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LiveUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full-stack e-commerce solution with cart, payments (Stripe), and admin dashboard.",
                            GithubUrl = "https://github.com/yourusername/ecommerce",
                            IsFeatured = true,
                            LiveUrl = "https://mystore.example.com",
                            TechStack = "ASP.NET Core,React,MySQL,Stripe",
                            Title = "E-Commerce Platform"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "RESTful task management API with JWT auth, role-based access, and real-time updates.",
                            GithubUrl = "https://github.com/yourusername/taskapi",
                            IsFeatured = true,
                            TechStack = "C#,.NET 8,MySQL,SignalR,JWT",
                            Title = "Task Manager API"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "This portfolio — a headless CMS backed by ASP.NET Core APIs and a static GitHub Pages frontend.",
                            GithubUrl = "https://github.com/yourusername/portfolio",
                            IsFeatured = false,
                            TechStack = "ASP.NET Core,MySQL,HTML,CSS,JavaScript",
                            Title = "Portfolio CMS"
                        });
                });

            modelBuilder.Entity("PortfolioAPI.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IconClass")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Proficiency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Backend",
                            Name = "C#",
                            Proficiency = 92
                        },
                        new
                        {
                            Id = 2,
                            Category = "Backend",
                            Name = "ASP.NET Core",
                            Proficiency = 90
                        },
                        new
                        {
                            Id = 3,
                            Category = "Database",
                            Name = "MySQL",
                            Proficiency = 85
                        },
                        new
                        {
                            Id = 4,
                            Category = "Backend",
                            Name = "Entity Framework",
                            Proficiency = 88
                        },
                        new
                        {
                            Id = 5,
                            Category = "Frontend",
                            Name = "JavaScript",
                            Proficiency = 80
                        },
                        new
                        {
                            Id = 6,
                            Category = "Frontend",
                            Name = "React",
                            Proficiency = 75
                        },
                        new
                        {
                            Id = 7,
                            Category = "DevOps",
                            Name = "Docker",
                            Proficiency = 70
                        },
                        new
                        {
                            Id = 8,
                            Category = "DevOps",
                            Name = "Git",
                            Proficiency = 90
                        },
                        new
                        {
                            Id = 9,
                            Category = "Backend",
                            Name = "REST APIs",
                            Proficiency = 95
                        },
                        new
                        {
                            Id = 10,
                            Category = "Frontend",
                            Name = "HTML/CSS",
                            Proficiency = 85
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
